version: '3'

services:
  backend_app:
    # container_name: "docker-mongo-node"
    restart: "always"
    build: .
    volumes:
      - './:/usr/src/app'
    # ports:
    #   - 8080:8080
    links:
      - "mongo"
      - "redis"
  mongo:
    container_name: "mongodb"
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  redis:
    container_name: "redis"
    image: "redis"
    ports:
      - 6379:6379
  nginx:
    image: "nginx"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - backend_app
    ports:
      - 8080:3000
volumes:
  data: