version: '3'

services:
  backend_app:
    container_name: "docker-mongo-node"
    restart: "always"
    build: .
    ports:
      - 8080:8080
    links:
      - "mongo"
  mongo:
    container_name: "mongodb"
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: